package controller.command;

public enum CommandName {

    SIGN_IN, SIGN_OUT, REGISTRATION, ADD_NEW_PRINT_EDITION, EDITED_PRINT_EDITION, DELETE_EDITION, SHOW_PRINT_EDITIONS, SORT_EDITIONS, WRONG_REQUEST

}
